--add by jinbin_guo 20140210 T_ATS_RepairWO
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFDeptID' AND KSQL_COL_TABNAME='T_ATS_RepairWO')
	ALTER TABLE T_ATS_RepairWO ADD CFDeptID varchar(44);
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFCustomInfo' AND KSQL_COL_TABNAME='T_ATS_RepairWO')
	ALTER TABLE T_ATS_RepairWO ADD CFCustomInfo nvarchar(255);
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFSaleType' AND KSQL_COL_TABNAME='T_ATS_RepairWO')
	ALTER TABLE T_ATS_RepairWO ADD CFSaleType nvarchar(100);
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFCustomerAccountI' AND KSQL_COL_TABNAME='T_ATS_RepairWO')
	ALTER TABLE T_ATS_RepairWO ADD CFCustomerAccountI varchar(44);
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFCustomerAccountName' AND KSQL_COL_TABNAME='T_ATS_RepairWO')
	ALTER TABLE T_ATS_RepairWO ADD CFCustomerAccountName nvarchar(80);
	
--add by jinbin_guo 20140210 T_ATS_RWORepairItemEntry
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFWipLineNo' AND KSQL_COL_TABNAME='T_ATS_RWORepairItemEntry')
	ALTER TABLE T_ATS_RWORepairItemEntry ADD CFWipLineNo int;
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFWipFactLineNo' AND KSQL_COL_TABNAME='T_ATS_RWORepairItemEntry')
	ALTER TABLE T_ATS_RWORepairItemEntry ADD CFWipFactLineNo int;
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFItemSpEntryId' AND KSQL_COL_TABNAME='T_ATS_RWORepairItemEntry')
	ALTER TABLE T_ATS_RWORepairItemEntry ADD CFItemSpEntryId varchar(44);

--add by jinbin_guo 20140210 T_ATS_RWOSparepartEntry
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFWipLineNo' AND KSQL_COL_TABNAME='T_ATS_RWOSparepartEntry')
	ALTER TABLE T_ATS_RWOSparepartEntry ADD CFWipLineNo int;
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFWipFactLineNo' AND KSQL_COL_TABNAME='T_ATS_RWOSparepartEntry')
	ALTER TABLE T_ATS_RWOSparepartEntry ADD CFWipFactLineNo int;	
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFIsCT' AND KSQL_COL_TABNAME='T_ATS_RWOSparepartEntry')
	ALTER TABLE T_ATS_RWOSparepartEntry ADD CFIsCT int;	
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFItemSpEntryId' AND KSQL_COL_TABNAME='T_ATS_RWOSparepartEntry')
	ALTER TABLE T_ATS_RWOSparepartEntry ADD CFItemSpEntryId varchar(44);

--add by jinbin_guo 20140211 T_PM_User
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFUserType' AND KSQL_COL_TABNAME='T_PM_User')
	ALTER TABLE T_PM_User ADD CFUserType varchar(100);

--add by jinbin_guo 20140212 CT_RS_W
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFSettleObject' AND KSQL_COL_TABNAME='CT_RS_W')
	ALTER TABLE CT_RS_W ADD CFSettleObject varchar(100);
	
--add by jinbin_guo 20140213 CT_ATS_RepairWORWOItemSpEntry
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFSettlementObject' AND KSQL_COL_TABNAME='CT_ATS_RepairWORWOItemSpEntry')
	ALTER TABLE CT_ATS_RepairWORWOItemSpEntry ADD CFSettlementObject varchar(100);
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFWipLineNo' AND KSQL_COL_TABNAME='CT_ATS_RepairWORWOItemSpEntry')
	ALTER TABLE CT_ATS_RepairWORWOItemSpEntry ADD CFWipLineNo int;
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_NAME ='CFWipFactLineNo' AND KSQL_COL_TABNAME='CT_ATS_RepairWORWOItemSpEntry')
	ALTER TABLE CT_ATS_RepairWORWOItemSpEntry ADD CFWipFactLineNo int;
	

	