<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.myframework.test.client</package>
    <name>TestResource</name>
    <alias>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.myframework.test.client.TestResource</className>
    <resourceItems>
        <resourceItem>
            <name>Test001QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test001QueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Test002QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test002QueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Test003QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test003QueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Test004QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test004QueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Test005QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test005QueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Test006QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test006QueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestDatabaseQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestDatabaseQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestDatabase2QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestDatabase2QueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestDatabase3QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestDatabase3QueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestGroupQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestGroupQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestTreeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestTreeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestTree2QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestTree2QueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test001QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Test001" />
            <lang locale="zh_HK" value="Test001" />
            <lang locale="zh_TW" value="Test001" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test002QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Test002" />
            <lang locale="zh_HK" value="Test002" />
            <lang locale="zh_TW" value="Test002" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test003QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Test003" />
            <lang locale="zh_HK" value="Test003" />
            <lang locale="zh_TW" value="Test003" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test004QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Test004" />
            <lang locale="zh_HK" value="Test004" />
            <lang locale="zh_TW" value="Test004" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test005QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Test005" />
            <lang locale="zh_HK" value="Test005" />
            <lang locale="zh_TW" value="Test005" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[Test006QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Test006" />
            <lang locale="zh_HK" value="Test006" />
            <lang locale="zh_TW" value="Test006" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="TestBill" />
            <lang locale="zh_HK" value="TestBill" />
            <lang locale="zh_TW" value="TestBill" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestDatabase2QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="TestDatabase2" />
            <lang locale="zh_HK" value="TestDatabase2" />
            <lang locale="zh_TW" value="TestDatabase2" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestDatabase3QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="TestDatabase3" />
            <lang locale="zh_HK" value="TestDatabase3" />
            <lang locale="zh_TW" value="TestDatabase3" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestDatabaseQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="TestDatabase" />
            <lang locale="zh_HK" value="TestDatabase" />
            <lang locale="zh_TW" value="TestDatabase" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestGroupQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="TestGroup" />
            <lang locale="zh_HK" value="TestGroup" />
            <lang locale="zh_TW" value="TestGroup" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Test" />
            <lang locale="zh_HK" value="Test" />
            <lang locale="zh_TW" value="Test" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestTree2QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="TestTree2" />
            <lang locale="zh_HK" value="TestTree2" />
            <lang locale="zh_TW" value="TestTree2" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.myframework.test.client.TestResource].resourceItems.resourceItem[TestTreeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="TestTree" />
            <lang locale="zh_HK" value="TestTree" />
            <lang locale="zh_TW" value="TestTree" />
        </rs>
    </resource>
</i18nResource>

